export { default as MainPanel } from './MainPanel';
export { default as Profile } from './Dashboard';
export { default as Employee } from './Employee';
export { default as Dashboard } from './Dashboard';
export { default as Header } from './Header';
export { default as EmployeeCard } from '../ui/EmployeeCard';
export { default as NewEmployeeBtn } from '../ui/NewEmployeeBtn';
export { default as SignUp } from './Login/SignUp';
export { default as EmployeeDetail } from './EmployeeDetail';
export { default as EditEmployeeDetails } from './EditEmployeeDetails';
export { default as MakeRequest } from './MakeRequest';
export { default as NewRequestBtn } from '../ui/NewRequestBtn';
export { default as OverlayRequest } from '../components/OverlayRequest';
export { default as RequestDetailsCard } from '../components/RequestDetailsCard';
export { default as RequiredAuth } from './RequiredAuth';
export { default as Unauthorized } from './Unauthorized'
export { default as Department } from './Department'
export { default as DepartmentDetails } from './DepartmentDetails';
export { default as RegisterDept } from './RegisterDept';
export { default as UpdateDept } from './UpdateDept';
export { default as AddEmployee } from './AddEmployee';
export { default as DeptEmployeeDetails } from './DeptEmployeeDetails'
export { default as DeptEditEmployee } from './DeptEditEmployee'